Etsub Demile - DS4400 - January 30th, 2026

Problem 4 Part 2

In [3]:
import numpy as np
np.random.seed(123)  

for i in range(1, 4):
    print(f"MATRIX {i}")
    print('='*50)
    
    # random 3x3 matrix with integers from -10 to 10
    M = np.random.randint(-10, 11, size=(3, 3))
    print(f"\nM{i} =")
    print(M)
    
    # inverse using numpy package
    det = np.linalg.det(M)
    print(f"\nDeterminant = {det:.4f}")
    
    if abs(det) < 1e-10:
        print("Matrix is singular - no inverse exists!")
    else:
        M_inv = np.linalg.inv(M)
        print(f"\nM{i}^(-1) =")
        print(np.round(M_inv, 4))
        
        # Verification
        product = M @ M_inv
        print(f"\nM{i} × M{i}^(-1) =")
        print(np.round(product))

MATRIX 1

M1 =
[[  3  -8  -8]
 [ -4   7   9]
 [  0  -9 -10]]

Determinant = 65.0000

M1^(-1) =
[[ 0.1692 -0.1231 -0.2462]
 [-0.6154 -0.4615  0.0769]
 [ 0.5538  0.4154 -0.1692]]

M1 × M1^(-1) =
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]
MATRIX 2

M2 =
[[  7   5  -1]
 [-10   4 -10]
 [  5   9   4]]

Determinant = 802.0000

M2^(-1) =
[[ 0.1322 -0.0362 -0.0574]
 [-0.0125  0.0411  0.0998]
 [-0.1372 -0.0474  0.0973]]

M2 × M2^(-1) =
[[ 1. -0. -0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]
MATRIX 3

M3 =
[[ -6 -10   6]
 [ -6   7  -7]
 [ -8  10  -3]]

Determinant = -698.0000

M3^(-1) =
[[-0.0702 -0.043  -0.0401]
 [-0.0544 -0.0946  0.1117]
 [ 0.0057 -0.2006  0.1461]]

M3 × M3^(-1) =
[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Problem 5 Part 1

In [25]:
import pandas as pd

# Load dataset
df = pd.read_csv("kc_house_data.csv")

# Drop columns to ignore
df = df.drop(columns=["id", "date", "zipcode"])

# Compute statistics
stats = pd.DataFrame({
    "average": df.mean(),
    "min": df.min(),
    "max": df.max(),
    "variance": df.var()
})

# Identify features with lowest/highest average
lowest_avg_feature = stats["average"].idxmin()
highest_avg_feature = stats["average"].idxmax()

# Identify features with lowest/highest variance
lowest_var_feature = stats["variance"].idxmin()
highest_var_feature = stats["variance"].idxmax()

# Display results
print("Summary statistics:\n")
display(stats)

print("\nFeature with lowest average:")
print(f"{lowest_avg_feature}: {stats.loc[lowest_avg_feature, 'average']}")

print("\nFeature with highest average:")
print(f"{highest_avg_feature}: {stats.loc[highest_avg_feature, 'average']}")

print("\nFeature with lowest variance:")
print(f"{lowest_var_feature}: {stats.loc[lowest_var_feature, 'variance']}")

print("\nFeature with highest variance:")
print(f"{highest_var_feature}: {stats.loc[highest_var_feature, 'variance']}")


Summary statistics:



,average,min,max,variance
price,540088.141767,75000.0000,7.700000e+06,1.347824e+11
bedrooms,3.370842,0.0000,3.300000e+01,8.650150e-01
bathrooms,2.114757,0.0000,8.000000e+00,5.931513e-01
sqft_living,2079.899736,290.0000,1.354000e+04,8.435337e+05
sqft_lot,15106.967566,520.0000,1.651359e+06,1.715659e+09
floors,1.494309,1.0000,3.500000e+00,2.915880e-01
waterfront,0.007542,0.0000,1.000000e+00,7.485226e-03
view,0.234303,0.0000,4.000000e+00,5.872426e-01
condition,3.409430,1.0000,5.000000e+00,4.234665e-01
grade,7.656873,1.0000,1.300000e+01,1.381703e+00



Feature with lowest average:
long: -122.21389640494147

Feature with highest average:
price: 540088.1417665294

Feature with lowest variance:
waterfront: 0.007485225502686407

Feature with highest variance:
price: 134782378397.24686


Problem 5 Part 2

In [21]:


# Load dataset
df = pd.read_csv("kc_house_data.csv")

# Drop columns to ignore
df = df.drop(columns=["id", "date", "zipcode"])

# Compute correlation of each feature with price
correlation = df.corr()["price"].drop("price").sort_values(ascending=False)

# Convert to table
correlation_table = correlation.to_frame(name="correlation_with_price")

# Display table
print("Correlation coefficient of each feature with price:\n")
display(correlation_table)

# Identify positively correlated features
positive_correlations = correlation[correlation > 0].index.tolist()

print("\nFeatures positively correlated with price:")
print(positive_correlations)

# Feature with highest positive correlation
highest_corr_feature = correlation.idxmax()
highest_corr_value = correlation.max()

print("\nFeature with highest positive correlation with price:")
print(f"{highest_corr_feature}: {highest_corr_value}")


Correlation coefficient of each feature with price:



,correlation_with_price
sqft_living,0.702035
grade,0.667434
sqft_above,0.605567
sqft_living15,0.585379
bathrooms,0.525138
view,0.397293
sqft_basement,0.323816
bedrooms,0.308350
lat,0.307003
waterfront,0.266369



Features positively correlated with price:
['sqft_living', 'grade', 'sqft_above', 'sqft_living15', 'bathrooms', 'view', 'sqft_basement', 'bedrooms', 'lat', 'waterfront', 'floors', 'yr_renovated', 'sqft_lot', 'sqft_lot15', 'yr_built', 'condition', 'long']

Feature with highest positive correlation with price:
sqft_living: 0.7020350546118005


Problem 5 Part 3

In [24]:
# correlation of each feature with the response (price)
correlations = df_features.corrwith(df['price']).sort_values(ascending=False)

# Convert to a clean table
corr_table = correlations.reset_index()
corr_table.columns = ["feature", "correlation_with_price"]

# correlation table
print("Correlation of each feature with price:\n")
print(corr_table)

# features negatively correlated with price
negative_corr = corr_table[corr_table["correlation_with_price"] < 0]

print("\nFeatures negatively correlated with price:\n")
print(negative_corr)

print("\nFrom the correlation analysis, all features show either a positive or very small correlation with house prices. There are no features with a negative correlation with the response. The strongest positive correlation is observed with sqft_living (0.70), followed by grade (0.67) and sqft_above (0.61). This indicates that larger homes and homes with higher construction quality tend to sell for higher prices, while location-related and lot size variables have weaker positive relationships with price:\n")

Correlation of each feature with price:

          feature  correlation_with_price
0     sqft_living                0.702035
1           grade                0.667434
2      sqft_above                0.605567
3   sqft_living15                0.585379
4       bathrooms                0.525138
5            view                0.397293
6   sqft_basement                0.323816
7        bedrooms                0.308350
8             lat                0.307003
9      waterfront                0.266369
10         floors                0.256794
11   yr_renovated                0.126434
12       sqft_lot                0.089661
13     sqft_lot15                0.082447
14       yr_built                0.054012
15      condition                0.036362
16           long                0.021626

Features negatively correlated with price:

Empty DataFrame
Columns: [feature, correlation_with_price]
Index: []

From the correlation analysis, all features show either a positive or very small correla